---

- hosts: staging
  become: true

  tasks:
  - name: Install maven 
    apt:
      name: maven
      state: present
      update_cache: true

  - name: Install Git 
    apt:
      name: git
      state: present
      update_cache: true

  - name: Git Clone boxfuse
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/java-app
      clone: true
      update: true
    register: git_status

  - name: Maven when cloned ok
    shell:
      chdir: /tmp/java-app/boxfuse-sample-java-war-hello
      cmd: mvn package
    when: git_status.changed
    register: build_status

  - name: fetch war
    fetch:
      src: /tmp/java-app/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /tmp/
      flat: true
    when: build_status is succeeded

- hosts: deploy
  become: yes
  tasks:

  - name: Install OpenJDK
    apt:
      name: openjdk-11-jre-headless
      state: present
      update_cache: true

  - name: download tomcat server packages
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.44/bin/apache-tomcat-9.0.44.tar.gz
      dest: /usr/local

  - name: extract tomcat packages
    unarchive:
      src: /usr/local/apache-tomcat-9.0.44.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: add fusebox war
    copy:
      src: /tmp/hello-1.0.war
      dest: /usr/local/apache-tomcat-9.0.44/webapps

  - name: start tomcat services
    shell:
      chdir: /usr/local/apache-tomcat-9.0.44/bin/startup.sh
      cmd: nohup