---

- name: Build Java FuseBox Artifact
- hosts: staging
  become: true
  roles:
    - appbuilding


- name: Build Java FuseBox Artifact on Tomcat
- hosts: deploy
  become: true
  roles:
    - appdeployment