---

- hosts: staging
  become: true

  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started


    - name: Add Date
      lineinfile:
        path: /usr/share/nginx/html/index.html
        regexp: '^<h1>Welcome to nginx!</h1>'
        line: '<p><script> document.write(new Date().toLocaleDateString()); </script></p>'